### ISSUE TITLE
eye tracking calibration

### ISSUE THREAD

**Issue by Rigor00** [NeuralAction/NeuralAction#1]
Hi,

I downloaded your release version and when I run the exe, it has a cursor that moves but not to where my gaze is. Quite far from it, probably since I haven't calibrated. Your documents don't mention how to calibrate. Can you tell me how to calibrate? Thanks

**Comment by gmlwns2000** [comment]
Hi @Rigor00 !

You can calibrate your tracker from the menu. 

And also you can check how it is working on [demo video from 0:15](https://youtu.be/J42NxjT1wus?t=16)

To open menu, you can try to click a circle logo icon on right below in screen. Or you can click taskbar notification icon to open the menu. 

In the menu, the button on the left side is a calibration button.

And also, before calibration, you should place the webcam on the proper place (upper center of the screen, just like a laptop), and set correct DPI of the screen.

![image](https://user-images.githubusercontent.com/4879345/54604603-7f1c1580-4a8a-11e9-979f-1b6e603217e7.png)
